emulator:
  type: ldplayer
  install_dir: "C:/Users/ASUS/OneDrive/Documents/COC/tools/platform-tools"
  index: 0
  name: LDPlayer
  adb_path: "C:/Users/ASUS/OneDrive/Documents/COC/tools/platform-tools/adb.exe"
  device_id: "127.0.0.1:5555"
  resolution: "1920x1080"
  dpi: 240

account:
  count: 1

farm:
  resources:
    - gold
    - elixir
  town_hall: 16
  loot_threshold:
    gold: 400000
    elixir: 400000
    dark: 0

safety:
  min_delay_sec: 2
  max_delay_sec: 8
  session_hours: 2
  break_minutes: 30
